/**
 * @author Francisco Moya
 */
public class Usuarios extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form Usuarios
     */
    public Usuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Informes = new javax.swing.JTabbedPane();
        ventas = new javax.swing.JPanel();
        logoletraconfirmacion = new javax.swing.JLabel();
        panelconfirmacion = new javax.swing.JTabbedPane();
        panelventas = new javax.swing.JPanel();
        ventanaventa_datossolicitantes = new javax.swing.JPanel();
        numeropedidosventa = new javax.swing.JLabel();
        nameclienteventa = new javax.swing.JLabel();
        emailventassolicitante = new javax.swing.JLabel();
        rutventassolicitante = new javax.swing.JLabel();
        numeroventascliente = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        btnguardar_dtsclientventa = new javax.swing.JButton();
        btncancelar_dtsclientventa = new javax.swing.JButton();
        btnbuscarventascliente = new javax.swing.JButton();
        digitoverificadorventas = new javax.swing.JTextField();
        guionmedio = new javax.swing.JLabel();
        Preguntarrutventas = new javax.swing.JButton();
        ventanaventa_datosdestinarios = new javax.swing.JPanel();
        namedestinarioventa = new javax.swing.JLabel();
        fechaentregadestinarios = new javax.swing.JLabel();
        direcciondestinario = new javax.swing.JLabel();
        comunaletra = new javax.swing.JLabel();
        saludosletra = new javax.swing.JLabel();
        packletras = new javax.swing.JLabel();
        horainicioletra = new javax.swing.JLabel();
        horafinentregaletra = new javax.swing.JLabel();
        namedestinarios_venta = new javax.swing.JTextField();
        direccion_destinventa = new javax.swing.JTextField();
        txtsaludos = new javax.swing.JTextField();
        btnguardar_dtsdestin = new javax.swing.JButton();
        btncsncelar_dtsdestin = new javax.swing.JButton();
        Panelboletas = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        fecha_entrega_venta = new com.toedter.calendar.JDateChooser();
        hrsentrega_ventas = new javax.swing.JComboBox<>();
        entregahora_ventas = new javax.swing.JComboBox<>();
        horaentrega = new javax.swing.JLabel();
        hrsletra = new javax.swing.JLabel();
        comboxcomuna_ventas = new javax.swing.JComboBox<>();
        packdestinario = new javax.swing.JComboBox<>();
        ventaspendientepago = new javax.swing.JPanel();
        ConfirmaPagoClienteConfim = new javax.swing.JPanel();
        txtnumeropedido_confirmacion = new javax.swing.JTextField();
        txtrutconfirmacion = new javax.swing.JTextField();
        bancoclienteconfirmacion = new javax.swing.JComboBox<>();
        numeropedidoletra = new javax.swing.JLabel();
        rutconfirmapagoletra = new javax.swing.JLabel();
        bancoclienteletra = new javax.swing.JLabel();
        txtnamecliente = new javax.swing.JTextField();
        calendariofechapagoconfirm = new com.toedter.calendar.JDateChooser();
        codigotransaccionconfirm = new javax.swing.JTextField();
        nombreclienteletras = new javax.swing.JLabel();
        fechapagoletra = new javax.swing.JLabel();
        codigotransaccionletra = new javax.swing.JLabel();
        btnbuscarrutconfirmacion = new javax.swing.JButton();
        btnpreguntaconfirmacion = new javax.swing.JButton();
        btnguardarconfirmacionguardar = new javax.swing.JButton();
        btncancelar_confirmacion = new javax.swing.JButton();
        ventpendientpagoletras = new javax.swing.JLabel();
        paneltablapendientepago = new javax.swing.JScrollPane();
        panelpendientpago = new javax.swing.JTable();
        seleccionarconfirmacion = new javax.swing.JButton();
        primerpanellistadestino = new javax.swing.JPanel();
        paneldespacholistadestino = new javax.swing.JPanel();
        tabladespachodia = new javax.swing.JScrollPane();
        tabladespachodiadestino = new javax.swing.JTable();
        btnprintdestino = new javax.swing.JButton();
        btndescargadestino = new javax.swing.JButton();
        titulodespachopordia = new javax.swing.JLabel();
        btnbuscardestino = new javax.swing.JButton();
        txtbuscardestino = new javax.swing.JTextField();
        panelestadodespacho = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        paneldespacho = new javax.swing.JScrollPane();
        tabladespacho = new javax.swing.JTable();
        estadodespacholetra = new javax.swing.JLabel();
        btnbuscardespacho = new javax.swing.JButton();
        txtbuscardespacho = new javax.swing.JTextField();
        categoriaentregadespacho = new javax.swing.JComboBox<>();
        categorialetra = new javax.swing.JLabel();
        btnprintdesspacho = new javax.swing.JButton();
        btndescargardespacho = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        Logo = new javax.swing.JPanel();
        letraslogocompras = new javax.swing.JLabel();
        informes = new javax.swing.JPanel();
        logosinformes = new javax.swing.JLabel();
        administrador = new javax.swing.JPanel();
        usuarios = new javax.swing.JTabbedPane();
        clientes = new javax.swing.JPanel();
        proveedores = new javax.swing.JPanel();
        articulos = new javax.swing.JPanel();
        pack = new javax.swing.JPanel();
        rrss = new javax.swing.JPanel();
        categoriaarticulos = new javax.swing.JPanel();
        bancos = new javax.swing.JPanel();
        comunas = new javax.swing.JPanel();
        categriaventas = new javax.swing.JPanel();
        usuario = new javax.swing.JPanel();
        panelusuarios = new javax.swing.JPanel();
        nameuser = new javax.swing.JLabel();
        contraseñauser = new javax.swing.JLabel();
        repetircontraseña = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        txt2contraseña = new javax.swing.JPasswordField();
        txtcontraseña = new javax.swing.JPasswordField();
        btnguardar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        usuariosregistrados = new javax.swing.JPanel();
        usuariosregistradostabla = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btneditar = new javax.swing.JButton();
        btndesactivaruser_registrados = new javax.swing.JButton();
        txtbuscaruserregistrados = new javax.swing.JTextField();
        buscartexto = new javax.swing.JLabel();
        btnbuscar = new javax.swing.JButton();
        panellogo = new javax.swing.JPanel();
        letralogoadministrador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logoletraconfirmacion.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        logoletraconfirmacion.setText("Dreams Gifts");

        ventanaventa_datossolicitantes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Clientes Solicitante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        numeropedidosventa.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        numeropedidosventa.setText("Numero Pedido :");

        nameclienteventa.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        nameclienteventa.setText("Nombre Cliente :");

        emailventassolicitante.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        emailventassolicitante.setText("Email :");

        rutventassolicitante.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        rutventassolicitante.setText("Rut :");

        numeroventascliente.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        numeroventascliente.setText("Telefono :");

        jTextField1.setText("0012");

        jTextField2.setText("Francisco Tapiado");

        jTextField3.setText("Fjt@gmail.com");

        jTextField4.setText("19234172");

        jTextField5.setText("+56967532677");

        btnguardar_dtsclientventa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/savedisk_floppydisk_guardar_1543 (1).png"))); // NOI18N
        btnguardar_dtsclientventa.setText("Guardar");

        btncancelar_dtsclientventa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/ic_cancel_128_28318.png"))); // NOI18N
        btncancelar_dtsclientventa.setText("Cancelar");

        btnbuscarventascliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/searcher_magnifyng_glass_search_locate_find_icon_123813.png"))); // NOI18N

        digitoverificadorventas.setText("1");

        guionmedio.setText("-");

        Preguntarrutventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/question-sign_icon-icons.com_73445 (1).png"))); // NOI18N

        javax.swing.GroupLayout ventanaventa_datossolicitantesLayout = new javax.swing.GroupLayout(ventanaventa_datossolicitantes);
        ventanaventa_datossolicitantes.setLayout(ventanaventa_datossolicitantesLayout);
        ventanaventa_datossolicitantesLayout.setHorizontalGroup(
            ventanaventa_datossolicitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaventa_datossolicitantesLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(ventanaventa_datossolicitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(emailventassolicitante)
                    .addComponent(nameclienteventa)
                    .addComponent(numeropedidosventa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ventanaventa_datossolicitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanaventa_datossolicitantesLayout.createSequentialGroup()
                        .addGroup(ventanaventa_datossolicitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(ventanaventa_datossolicitantesLayout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(numeroventascliente))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ventanaventa_datossolicitantesLayout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(rutventassolicitante)))
                        .addGap(12, 12, 12)
                        .addGroup(ventanaventa_datossolicitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ventanaventa_datossolicitantesLayout.createSequentialGroup()
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(guionmedio, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(digitoverificadorventas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnbuscarventascliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Preguntarrutventas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(ventanaventa_datossolicitantesLayout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(btnguardar_dtsclientventa)
                        .addGap(36, 36, 36)
                        .addComponent(btncancelar_dtsclientventa)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        ventanaventa_datossolicitantesLayout.setVerticalGroup(
            ventanaventa_datossolicitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaventa_datossolicitantesLayout.createSequentialGroup()
                .addGroup(ventanaventa_datossolicitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ventanaventa_datossolicitantesLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(ventanaventa_datossolicitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numeropedidosventa)
                            .addComponent(rutventassolicitante)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(digitoverificadorventas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guionmedio)))
                    .addComponent(btnbuscarventascliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Preguntarrutventas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(ventanaventa_datossolicitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameclienteventa)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroventascliente)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(ventanaventa_datossolicitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanaventa_datossolicitantesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(ventanaventa_datossolicitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailventassolicitante)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaventa_datossolicitantesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(ventanaventa_datossolicitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnguardar_dtsclientventa)
                            .addComponent(btncancelar_dtsclientventa))
                        .addGap(24, 24, 24))))
        );

        ventanaventa_datosdestinarios.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Destinario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        namedestinarioventa.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        namedestinarioventa.setText("Nombre Destinario :");

        fechaentregadestinarios.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        fechaentregadestinarios.setText("Fecha de Entrega :");

        direcciondestinario.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        direcciondestinario.setText("Direccion :");

        comunaletra.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        comunaletra.setText("Comuna :");

        saludosletra.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        saludosletra.setText("Saludos :");

        packletras.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        packletras.setText("Pack :");

        horainicioletra.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        horainicioletra.setText("Hora Inicio Entrega :");

        horafinentregaletra.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        horafinentregaletra.setText("Hora Fin Entrega :");

        namedestinarios_venta.setText("Javiera Toloza");

        direccion_destinventa.setText("Nueva Constitucion 1233");

        btnguardar_dtsdestin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/savedisk_floppydisk_guardar_1543 (1).png"))); // NOI18N
        btnguardar_dtsdestin.setText("Guardar");

        btncsncelar_dtsdestin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/ic_cancel_128_28318.png"))); // NOI18N
        btncsncelar_dtsdestin.setText("Cancelar");

        Panelboletas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Boletas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel22.setText("SubTotal :");

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel23.setText("Envio :");

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel24.setText("Total :");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel24)
                .addContainerGap(284, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel24)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelboletasLayout = new javax.swing.GroupLayout(Panelboletas);
        Panelboletas.setLayout(PanelboletasLayout);
        PanelboletasLayout.setHorizontalGroup(
            PanelboletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelboletasLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(PanelboletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel22))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelboletasLayout.setVerticalGroup(
            PanelboletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelboletasLayout.createSequentialGroup()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        hrsentrega_ventas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", " ", " " }));
        hrsentrega_ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrsentrega_ventasActionPerformed(evt);
            }
        });

        entregahora_ventas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00" }));

        horaentrega.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        horaentrega.setText("Hrs");

        hrsletra.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        hrsletra.setText("Hrs");

        comboxcomuna_ventas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Santiago  ", " Conchalí", "Huechuraba", "Independencia", "Quilicura", "Recoleta", "Renca", "Las Condes", "Lo Barnechea", "Providencia", "Vitacura", "La Reina", "Macul", "Ñuñoa", "Peñalolén", "La Florida", "La Granja", "El Bosque", "La Cisterna", "La Pintana", "San Ramón", "Lo Espejo", "Pedro Aguirre Cerda", "San Joaquín", "San Miguel", "Cerrillos", "Estación Central", "Maipú", "Cerro Navia", "Lo Prado", "Pudahuel", "Quinta Normal" }));

        packdestinario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pack Cumpleaños", "Pack Aniversario", "Pack Dia de la Madre", "Pack Dia del Padre" }));

        javax.swing.GroupLayout ventanaventa_datosdestinariosLayout = new javax.swing.GroupLayout(ventanaventa_datosdestinarios);
        ventanaventa_datosdestinarios.setLayout(ventanaventa_datosdestinariosLayout);
        ventanaventa_datosdestinariosLayout.setHorizontalGroup(
            ventanaventa_datosdestinariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaventa_datosdestinariosLayout.createSequentialGroup()
                .addGroup(ventanaventa_datosdestinariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanaventa_datosdestinariosLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(ventanaventa_datosdestinariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namedestinarioventa)
                            .addComponent(fechaentregadestinarios)))
                    .addGroup(ventanaventa_datosdestinariosLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(ventanaventa_datosdestinariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comunaletra)
                            .addComponent(direcciondestinario)
                            .addComponent(saludosletra))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ventanaventa_datosdestinariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanaventa_datosdestinariosLayout.createSequentialGroup()
                        .addComponent(txtsaludos, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ventanaventa_datosdestinariosLayout.createSequentialGroup()
                        .addGroup(ventanaventa_datosdestinariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(comboxcomuna_ventas, 0, 293, Short.MAX_VALUE)
                            .addComponent(direccion_destinventa, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namedestinarios_venta, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fecha_entrega_venta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(ventanaventa_datosdestinariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ventanaventa_datosdestinariosLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(ventanaventa_datosdestinariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(horainicioletra)
                                    .addComponent(packletras)
                                    .addComponent(horafinentregaletra))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ventanaventa_datosdestinariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ventanaventa_datosdestinariosLayout.createSequentialGroup()
                                        .addGroup(ventanaventa_datosdestinariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(hrsentrega_ventas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(entregahora_ventas, 0, 71, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(ventanaventa_datosdestinariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(horaentrega)
                                            .addComponent(hrsletra)))
                                    .addComponent(packdestinario, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaventa_datosdestinariosLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(ventanaventa_datosdestinariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Panelboletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(ventanaventa_datosdestinariosLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(btnguardar_dtsdestin)
                                        .addGap(41, 41, 41)
                                        .addComponent(btncsncelar_dtsdestin)))))))
                .addContainerGap())
        );
        ventanaventa_datosdestinariosLayout.setVerticalGroup(
            ventanaventa_datosdestinariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaventa_datosdestinariosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(ventanaventa_datosdestinariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namedestinarioventa)
                    .addComponent(packletras)
                    .addComponent(namedestinarios_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(packdestinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ventanaventa_datosdestinariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanaventa_datosdestinariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fechaentregadestinarios)
                        .addComponent(horainicioletra)
                        .addComponent(hrsentrega_ventas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(horaentrega))
                    .addComponent(fecha_entrega_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(ventanaventa_datosdestinariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(direcciondestinario)
                    .addComponent(horafinentregaletra)
                    .addComponent(direccion_destinventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entregahora_ventas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrsletra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ventanaventa_datosdestinariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanaventa_datosdestinariosLayout.createSequentialGroup()
                        .addGroup(ventanaventa_datosdestinariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comunaletra)
                            .addComponent(comboxcomuna_ventas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ventanaventa_datosdestinariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saludosletra)
                            .addComponent(txtsaludos, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Panelboletas, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ventanaventa_datosdestinariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnguardar_dtsdestin)
                    .addComponent(btncsncelar_dtsdestin))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelventasLayout = new javax.swing.GroupLayout(panelventas);
        panelventas.setLayout(panelventasLayout);
        panelventasLayout.setHorizontalGroup(
            panelventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelventasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ventanaventa_datosdestinarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ventanaventa_datossolicitantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelventasLayout.setVerticalGroup(
            panelventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelventasLayout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(ventanaventa_datossolicitantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ventanaventa_datosdestinarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelconfirmacion.addTab("Ventas", panelventas);

        ConfirmaPagoClienteConfim.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Confirma Pago Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        bancoclienteconfirmacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banco Estado", "Banco de Chile", "Banco Internacional", "Scotiabank Chile", "Banco de Crédito e Inversiones", "Corpbanca", "Banco Bice", "HSBC Bank (Chile)", "Banco Santander", "Banco Itaú Chile", "Banco Security", "Banco Falabella", "Deutsche Bank", "Banco RIpley", "Rabobank Chile", "Banco Consorcio", "Banco Penta", "Banco Paris", "Banco Bilbao Vizcaya Argentaria (BBVA)", "Banco BTG Pactual Chile" }));

        numeropedidoletra.setText("Numero Pedido :");

        rutconfirmapagoletra.setText("Rut :");

        bancoclienteletra.setText("Banco Cliente :");

        nombreclienteletras.setText("Nombre Cliente :");

        fechapagoletra.setText("Fecha Pago :");

        codigotransaccionletra.setText("Codigo Transaccion :");

        btnbuscarrutconfirmacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/searcher_magnifyng_glass_search_locate_find_icon_123813.png"))); // NOI18N

        btnpreguntaconfirmacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/question-sign_icon-icons.com_73445 (1).png"))); // NOI18N

        btnguardarconfirmacionguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/savedisk_floppydisk_guardar_1543 (1).png"))); // NOI18N
        btnguardarconfirmacionguardar.setText("Guardar");

        btncancelar_confirmacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/ic_cancel_128_28318.png"))); // NOI18N
        btncancelar_confirmacion.setText("Cancelar");

        javax.swing.GroupLayout ConfirmaPagoClienteConfimLayout = new javax.swing.GroupLayout(ConfirmaPagoClienteConfim);
        ConfirmaPagoClienteConfim.setLayout(ConfirmaPagoClienteConfimLayout);
        ConfirmaPagoClienteConfimLayout.setHorizontalGroup(
            ConfirmaPagoClienteConfimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfirmaPagoClienteConfimLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(ConfirmaPagoClienteConfimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(numeropedidoletra)
                    .addComponent(rutconfirmapagoletra)
                    .addComponent(bancoclienteletra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ConfirmaPagoClienteConfimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConfirmaPagoClienteConfimLayout.createSequentialGroup()
                        .addGroup(ConfirmaPagoClienteConfimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtrutconfirmacion)
                            .addComponent(bancoclienteconfirmacion, 0, 221, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnbuscarrutconfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnpreguntaconfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtnumeropedido_confirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(ConfirmaPagoClienteConfimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ConfirmaPagoClienteConfimLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(nombreclienteletras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtnamecliente, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ConfirmaPagoClienteConfimLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(ConfirmaPagoClienteConfimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ConfirmaPagoClienteConfimLayout.createSequentialGroup()
                                .addComponent(btnguardarconfirmacionguardar)
                                .addGap(78, 78, 78)
                                .addComponent(btncancelar_confirmacion))
                            .addGroup(ConfirmaPagoClienteConfimLayout.createSequentialGroup()
                                .addGroup(ConfirmaPagoClienteConfimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(codigotransaccionletra)
                                    .addComponent(fechapagoletra))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(ConfirmaPagoClienteConfimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(calendariofechapagoconfirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(codigotransaccionconfirm))))))
                .addContainerGap())
        );
        ConfirmaPagoClienteConfimLayout.setVerticalGroup(
            ConfirmaPagoClienteConfimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfirmaPagoClienteConfimLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConfirmaPagoClienteConfimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnumeropedido_confirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeropedidoletra)
                    .addComponent(nombreclienteletras)
                    .addComponent(txtnamecliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(ConfirmaPagoClienteConfimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConfirmaPagoClienteConfimLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ConfirmaPagoClienteConfimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ConfirmaPagoClienteConfimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtrutconfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rutconfirmapagoletra)
                                .addComponent(fechapagoletra))
                            .addComponent(calendariofechapagoconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ConfirmaPagoClienteConfimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ConfirmaPagoClienteConfimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bancoclienteconfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bancoclienteletra))
                            .addGroup(ConfirmaPagoClienteConfimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(codigotransaccionconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(codigotransaccionletra))))
                    .addGroup(ConfirmaPagoClienteConfimLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(ConfirmaPagoClienteConfimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnpreguntaconfirmacion)
                            .addComponent(btnbuscarrutconfirmacion))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(ConfirmaPagoClienteConfimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguardarconfirmacionguardar)
                    .addComponent(btncancelar_confirmacion))
                .addGap(23, 23, 23))
        );

        ventpendientpagoletras.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ventpendientpagoletras.setText("Ventas Pendientes de Pagos");

        panelpendientpago.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelpendientpago.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Numero Pedido", "Fecha Pedido", "Nombre Cliente", "Numero Telefono", "Monto", "Pack", "Seleccion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        paneltablapendientepago.setViewportView(panelpendientpago);

        seleccionarconfirmacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/objectselect_104418.png"))); // NOI18N
        seleccionarconfirmacion.setText("Seleccionar");

        javax.swing.GroupLayout ventaspendientepagoLayout = new javax.swing.GroupLayout(ventaspendientepago);
        ventaspendientepago.setLayout(ventaspendientepagoLayout);
        ventaspendientepagoLayout.setHorizontalGroup(
            ventaspendientepagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventaspendientepagoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(seleccionarconfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(ventaspendientepagoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ventaspendientepagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventaspendientepagoLayout.createSequentialGroup()
                        .addComponent(paneltablapendientepago)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventaspendientepagoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ventpendientpagoletras, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(345, 345, 345))
                    .addGroup(ventaspendientepagoLayout.createSequentialGroup()
                        .addComponent(ConfirmaPagoClienteConfim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        ventaspendientepagoLayout.setVerticalGroup(
            ventaspendientepagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventaspendientepagoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ConfirmaPagoClienteConfim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(ventpendientpagoletras)
                .addGap(30, 30, 30)
                .addComponent(paneltablapendientepago, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seleccionarconfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        panelconfirmacion.addTab("Confirmacion", ventaspendientepago);

        paneldespacholistadestino.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Despacho", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        tabladespachodiadestino.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"006", "Pack-09 Dia de la Madre", "Julio Perez", "09/06/2021", "Peñalolen", "Av.Oriental 6958", "08:00 a 9:30"},
                {"007", "Pack-01 Cumpleaños", "Fernanda Lopez", "09/06/2021", "Providencia", "Av. Providencia 2330", "10:00 a 12:00"},
                {"008", "Pack-03 Aniversario", "Esteban Gonzalez", "09/06/2021", "Ñuñoa", "Sta. Tansversal  23457121", "12:00 a 14:00"},
                {"009", "Pack-08 Dia de la Madres", "Laura Miranda", "09/06/2021", "Quinta Normal", "Matucana 151", "14:00 a 16:00"},
                {"010", "Pack-02 Cumpleaños", "Magdalena Gutierrez", "09/06/2021", "Maipu ", "Av. Tres Poniente 445", "10:00 a 11:30"},
                {"011", "Pack-02 Aniversario", "Alejandro Tapia", "09/06/2021", "Quilicura", "Av. Pontevedra 988", "9:00 a 11:30"},
                {"012", "Pack-0 Dia de la Madre", "Blanca Trujillo", "09/06/2021", "Renca", "Pasaje Domingo Santa cruz wilson 212", "10:30 a 12:00"},
                {"013", "Pack-10 Cumpleaños", "Francisco Moya", "09/06/2021", "Cerrillos", "Pasaje Domingo Santa cruz wilson 578", "12:30 a 13:30"},
                {"014", "Pack-06 Aniversario", "Maximiliano Moya", "09/06/2021", "Estacion Central", "Av. Estacion Central 445", "15:30 a 16:00"}
            },
            new String [] {
                "Registro Venta", "Pack", "Destinatario", "Fecha Entrega", "Comuna", "Direccion", "Hora Entrega"
            }
        ));
        tabladespachodia.setViewportView(tabladespachodiadestino);

        btnprintdestino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Print_icon-icons.com_55835.png"))); // NOI18N
        btnprintdestino.setText("Imprimir");

        btndescargadestino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/seo-social-web-network-internet_12_icon-icons.com_61498.png"))); // NOI18N
        btndescargadestino.setText("Descargar");

        titulodespachopordia.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        titulodespachopordia.setText("Lista Destinos para Despacho por Día");

        btnbuscardestino.setText("Buscar");

        txtbuscardestino.setText("...");

        javax.swing.GroupLayout paneldespacholistadestinoLayout = new javax.swing.GroupLayout(paneldespacholistadestino);
        paneldespacholistadestino.setLayout(paneldespacholistadestinoLayout);
        paneldespacholistadestinoLayout.setHorizontalGroup(
            paneldespacholistadestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneldespacholistadestinoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btndescargadestino)
                .addGap(51, 51, 51)
                .addComponent(btnprintdestino)
                .addGap(70, 70, 70))
            .addGroup(paneldespacholistadestinoLayout.createSequentialGroup()
                .addGroup(paneldespacholistadestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneldespacholistadestinoLayout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(titulodespachopordia, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneldespacholistadestinoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtbuscardestino, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(btnbuscardestino)
                .addGap(57, 57, 57))
            .addGroup(paneldespacholistadestinoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(tabladespachodia)
                .addContainerGap())
        );
        paneldespacholistadestinoLayout.setVerticalGroup(
            paneldespacholistadestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldespacholistadestinoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(titulodespachopordia, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneldespacholistadestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbuscardestino)
                    .addComponent(txtbuscardestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(tabladespachodia, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(paneldespacholistadestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndescargadestino)
                    .addComponent(btnprintdestino))
                .addGap(102, 102, 102))
        );

        javax.swing.GroupLayout primerpanellistadestinoLayout = new javax.swing.GroupLayout(primerpanellistadestino);
        primerpanellistadestino.setLayout(primerpanellistadestinoLayout);
        primerpanellistadestinoLayout.setHorizontalGroup(
            primerpanellistadestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(primerpanellistadestinoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneldespacholistadestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        primerpanellistadestinoLayout.setVerticalGroup(
            primerpanellistadestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(primerpanellistadestinoLayout.createSequentialGroup()
                .addComponent(paneldespacholistadestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 103, Short.MAX_VALUE))
        );

        panelconfirmacion.addTab("Lista Destino", primerpanellistadestino);

        jDesktopPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Despacho"));

        tabladespacho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"001", "Pack-09 Dia de la Madre", "Julio Perez", "08/06/2021", "Maipu", "08:00 a 10:00", "Entregado"},
                {"002", "Pack-02 Cumpleaños", "Fernanda Lopez", "08/06/2021", "Las Condes", "10:00 a 12:00", "Rechazado"},
                {"003", "Pack-04 Aniversario", "Esteban Gonzalez", "08/06/2021", "Macul", "14::00 a 16:00", "Anulado"},
                {"004", "Pack-10 Cumpleaños", "Laura Miranda", "08/06/2021", "La Granja", "16:00 a 18:00", "Entregado"},
                {"005", "Pack-05 Aniversario", "Magdalena Gutierrez", "08/06/2021", "Providencia", "9:00 a 11:00", "No Entregado "},
                {"006", "Pack-01 Cumpleaños", "Alejandro tapia", "08/06/2021", "Puente Alto ", "11:00 a 13:00", "Entregado"},
                {"007", "Pack-04 Dia de la Madre", "Blanca Trujillo", "08/06/2021", "La Florida", "14:00 a 16:00", "Entregado"},
                {"008", "Pack-03 Aniversario", "Francisco Moya", "08/06/2021", "San Bernardo", "15:00 a 17:00", "Entregado"}
            },
            new String [] {
                "Numero de Pedido", "Pack", "Destinatario", "Fecha de Entrega", "Comuna", "Hora de Entrega", "Estado de Entrega"
            }
        ));
        paneldespacho.setViewportView(tabladespacho);

        estadodespacholetra.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        estadodespacholetra.setText("Actualización Estado Despacho ");

        btnbuscardespacho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/searcher_magnifyng_glass_search_locate_find_icon_123813.png"))); // NOI18N
        btnbuscardespacho.setText("Buscar");

        txtbuscardespacho.setText("...");

        categoriaentregadespacho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entregado", "Anulado", "Rechazado", "No Entregado" }));

        categorialetra.setText("Categoria");

        btnprintdesspacho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Print_icon-icons.com_55835.png"))); // NOI18N
        btnprintdesspacho.setText("Imprimir");

        btndescargardespacho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/seo-social-web-network-internet_12_icon-icons.com_61498.png"))); // NOI18N
        btndescargardespacho.setText("Descargar");
        btndescargardespacho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndescargardespachoActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(paneldespacho, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(estadodespacholetra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnbuscardespacho, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtbuscardespacho, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(categoriaentregadespacho, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(categorialetra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnprintdesspacho, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btndescargardespacho, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(estadodespacholetra, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(categorialetra, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(categoriaentregadespacho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162)
                        .addComponent(txtbuscardespacho, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnbuscardespacho)
                        .addGap(41, 41, 41))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(btndescargardespacho)
                        .addGap(34, 34, 34)
                        .addComponent(btnprintdesspacho, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneldespacho)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(estadodespacholetra, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbuscardespacho, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscardespacho)
                    .addComponent(categoriaentregadespacho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categorialetra, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(paneldespacho, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnprintdesspacho)
                    .addComponent(btndescargardespacho))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelestadodespachoLayout = new javax.swing.GroupLayout(panelestadodespacho);
        panelestadodespacho.setLayout(panelestadodespachoLayout);
        panelestadodespachoLayout.setHorizontalGroup(
            panelestadodespachoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelestadodespachoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        panelestadodespachoLayout.setVerticalGroup(
            panelestadodespachoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelestadodespachoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        panelconfirmacion.addTab("Actualizacion Despacho", panelestadodespacho);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 938, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ventasLayout = new javax.swing.GroupLayout(ventas);
        ventas.setLayout(ventasLayout);
        ventasLayout.setHorizontalGroup(
            ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventasLayout.createSequentialGroup()
                .addGroup(ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventasLayout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(logoletraconfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ventasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panelconfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        ventasLayout.setVerticalGroup(
            ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventasLayout.createSequentialGroup()
                .addComponent(logoletraconfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelconfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Informes.addTab("ventas", ventas);

        letraslogocompras.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        letraslogocompras.setText("Dreams Gifts");

        javax.swing.GroupLayout LogoLayout = new javax.swing.GroupLayout(Logo);
        Logo.setLayout(LogoLayout);
        LogoLayout.setHorizontalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoLayout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(letraslogocompras, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(484, Short.MAX_VALUE))
        );
        LogoLayout.setVerticalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoLayout.createSequentialGroup()
                .addComponent(letraslogocompras, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 651, Short.MAX_VALUE))
        );

        Informes.addTab("Compras", Logo);

        logosinformes.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        logosinformes.setText("Dreams Gifts");

        javax.swing.GroupLayout informesLayout = new javax.swing.GroupLayout(informes);
        informes.setLayout(informesLayout);
        informesLayout.setHorizontalGroup(
            informesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informesLayout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(logosinformes, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(484, Short.MAX_VALUE))
        );
        informesLayout.setVerticalGroup(
            informesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informesLayout.createSequentialGroup()
                .addComponent(logosinformes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 651, Short.MAX_VALUE))
        );

        Informes.addTab("Informes", informes);

        javax.swing.GroupLayout clientesLayout = new javax.swing.GroupLayout(clientes);
        clientes.setLayout(clientesLayout);
        clientesLayout.setHorizontalGroup(
            clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        clientesLayout.setVerticalGroup(
            clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        usuarios.addTab("Clientes", clientes);

        javax.swing.GroupLayout proveedoresLayout = new javax.swing.GroupLayout(proveedores);
        proveedores.setLayout(proveedoresLayout);
        proveedoresLayout.setHorizontalGroup(
            proveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        proveedoresLayout.setVerticalGroup(
            proveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        usuarios.addTab("Proveedores", proveedores);

        javax.swing.GroupLayout articulosLayout = new javax.swing.GroupLayout(articulos);
        articulos.setLayout(articulosLayout);
        articulosLayout.setHorizontalGroup(
            articulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        articulosLayout.setVerticalGroup(
            articulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        usuarios.addTab("Articulos", articulos);

        javax.swing.GroupLayout packLayout = new javax.swing.GroupLayout(pack);
        pack.setLayout(packLayout);
        packLayout.setHorizontalGroup(
            packLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        packLayout.setVerticalGroup(
            packLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        usuarios.addTab("Pack", pack);

        javax.swing.GroupLayout rrssLayout = new javax.swing.GroupLayout(rrss);
        rrss.setLayout(rrssLayout);
        rrssLayout.setHorizontalGroup(
            rrssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        rrssLayout.setVerticalGroup(
            rrssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        usuarios.addTab("RR.SS", rrss);

        javax.swing.GroupLayout categoriaarticulosLayout = new javax.swing.GroupLayout(categoriaarticulos);
        categoriaarticulos.setLayout(categoriaarticulosLayout);
        categoriaarticulosLayout.setHorizontalGroup(
            categoriaarticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        categoriaarticulosLayout.setVerticalGroup(
            categoriaarticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        usuarios.addTab("Categoria Articulos", categoriaarticulos);

        javax.swing.GroupLayout bancosLayout = new javax.swing.GroupLayout(bancos);
        bancos.setLayout(bancosLayout);
        bancosLayout.setHorizontalGroup(
            bancosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        bancosLayout.setVerticalGroup(
            bancosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        usuarios.addTab("Bancos", bancos);

        javax.swing.GroupLayout comunasLayout = new javax.swing.GroupLayout(comunas);
        comunas.setLayout(comunasLayout);
        comunasLayout.setHorizontalGroup(
            comunasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 957, Short.MAX_VALUE)
        );
        comunasLayout.setVerticalGroup(
            comunasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
        );

        usuarios.addTab("Comunas", comunas);

        javax.swing.GroupLayout categriaventasLayout = new javax.swing.GroupLayout(categriaventas);
        categriaventas.setLayout(categriaventasLayout);
        categriaventasLayout.setHorizontalGroup(
            categriaventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        categriaventasLayout.setVerticalGroup(
            categriaventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        usuarios.addTab("Categoria Ventas", categriaventas);

        panelusuarios.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        nameuser.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        nameuser.setText("Nombre Usuario :");

        contraseñauser.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        contraseñauser.setText("Contraseña :");

        repetircontraseña.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        repetircontraseña.setText("Repetir Contraseña :");

        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/savedisk_floppydisk_guardar_1543 (1).png"))); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/ic_cancel_128_28318.png"))); // NOI18N
        btncancelar.setText("Cancelar");

        javax.swing.GroupLayout panelusuariosLayout = new javax.swing.GroupLayout(panelusuarios);
        panelusuarios.setLayout(panelusuariosLayout);
        panelusuariosLayout.setHorizontalGroup(
            panelusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelusuariosLayout.createSequentialGroup()
                .addGroup(panelusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelusuariosLayout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(nameuser))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelusuariosLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(repetircontraseña)))
                    .addComponent(contraseñauser, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(txtcontraseña)
                    .addComponent(txt2contraseña))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btncancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(btnguardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56))
        );
        panelusuariosLayout.setVerticalGroup(
            panelusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelusuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelusuariosLayout.createSequentialGroup()
                        .addGroup(panelusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameuser)
                            .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(panelusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contraseñauser))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(repetircontraseña)
                    .addComponent(txt2contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        usuariosregistrados.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuarios Registrados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Usuarios", "Accion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        usuariosregistradostabla.setViewportView(tabla);

        btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/DocumentEdit_40924.png"))); // NOI18N
        btneditar.setText("Editar");

        btndesactivaruser_registrados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/blocked_chat_delete_muted_off_remove_user_icon_123772.png"))); // NOI18N
        btndesactivaruser_registrados.setText("Desactivar");

        txtbuscaruserregistrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscaruserregistradosActionPerformed(evt);
            }
        });

        buscartexto.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        buscartexto.setText("Buscar :");

        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/xmag_search_find_export_locate_5984.png"))); // NOI18N

        javax.swing.GroupLayout usuariosregistradosLayout = new javax.swing.GroupLayout(usuariosregistrados);
        usuariosregistrados.setLayout(usuariosregistradosLayout);
        usuariosregistradosLayout.setHorizontalGroup(
            usuariosregistradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuariosregistradosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(usuariosregistradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usuariosregistradosLayout.createSequentialGroup()
                        .addComponent(usuariosregistradostabla, javax.swing.GroupLayout.DEFAULT_SIZE, 899, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usuariosregistradosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btndesactivaruser_registrados)
                        .addGap(29, 29, 29))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usuariosregistradosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buscartexto)
                .addGap(3, 3, 3)
                .addComponent(txtbuscaruserregistrados, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        usuariosregistradosLayout.setVerticalGroup(
            usuariosregistradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuariosregistradosLayout.createSequentialGroup()
                .addGroup(usuariosregistradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buscartexto)
                    .addComponent(txtbuscaruserregistrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(usuariosregistradostabla, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(usuariosregistradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btneditar)
                    .addComponent(btndesactivaruser_registrados, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout usuarioLayout = new javax.swing.GroupLayout(usuario);
        usuario.setLayout(usuarioLayout);
        usuarioLayout.setHorizontalGroup(
            usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usuariosregistrados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelusuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        usuarioLayout.setVerticalGroup(
            usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usuariosregistrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        usuarios.addTab("Usuarios", usuario);

        letralogoadministrador.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        letralogoadministrador.setText("Dreams Gifts");

        javax.swing.GroupLayout panellogoLayout = new javax.swing.GroupLayout(panellogo);
        panellogo.setLayout(panellogoLayout);
        panellogoLayout.setHorizontalGroup(
            panellogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellogoLayout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(letralogoadministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panellogoLayout.setVerticalGroup(
            panellogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellogoLayout.createSequentialGroup()
                .addComponent(letralogoadministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout administradorLayout = new javax.swing.GroupLayout(administrador);
        administrador.setLayout(administradorLayout);
        administradorLayout.setHorizontalGroup(
            administradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panellogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(usuarios, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        administradorLayout.setVerticalGroup(
            administradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(administradorLayout.createSequentialGroup()
                .addComponent(panellogo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        Informes.addTab("Administrador", administrador);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Informes)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Informes, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnguardarActionPerformed

    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuarioActionPerformed

    private void txtbuscaruserregistradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscaruserregistradosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscaruserregistradosActionPerformed

    private void hrsentrega_ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrsentrega_ventasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrsentrega_ventasActionPerformed

    private void btndescargardespachoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndescargardespachoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btndescargardespachoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Usuarios().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ConfirmaPagoClienteConfim;
    private javax.swing.JTabbedPane Informes;
    private javax.swing.JPanel Logo;
    private javax.swing.JPanel Panelboletas;
    private javax.swing.JButton Preguntarrutventas;
    private javax.swing.JPanel administrador;
    private javax.swing.JPanel articulos;
    private javax.swing.JComboBox<String> bancoclienteconfirmacion;
    private javax.swing.JLabel bancoclienteletra;
    private javax.swing.JPanel bancos;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btnbuscardespacho;
    private javax.swing.JButton btnbuscardestino;
    private javax.swing.JButton btnbuscarrutconfirmacion;
    private javax.swing.JButton btnbuscarventascliente;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btncancelar_confirmacion;
    private javax.swing.JButton btncancelar_dtsclientventa;
    private javax.swing.JButton btncsncelar_dtsdestin;
    private javax.swing.JButton btndesactivaruser_registrados;
    private javax.swing.JButton btndescargadestino;
    private javax.swing.JButton btndescargardespacho;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnguardar_dtsclientventa;
    private javax.swing.JButton btnguardar_dtsdestin;
    private javax.swing.JButton btnguardarconfirmacionguardar;
    private javax.swing.JButton btnpreguntaconfirmacion;
    private javax.swing.JButton btnprintdesspacho;
    private javax.swing.JButton btnprintdestino;
    private javax.swing.JLabel buscartexto;
    private com.toedter.calendar.JDateChooser calendariofechapagoconfirm;
    private javax.swing.JPanel categoriaarticulos;
    private javax.swing.JComboBox<String> categoriaentregadespacho;
    private javax.swing.JLabel categorialetra;
    private javax.swing.JPanel categriaventas;
    private javax.swing.JPanel clientes;
    private javax.swing.JTextField codigotransaccionconfirm;
    private javax.swing.JLabel codigotransaccionletra;
    private javax.swing.JComboBox<String> comboxcomuna_ventas;
    private javax.swing.JLabel comunaletra;
    private javax.swing.JPanel comunas;
    private javax.swing.JLabel contraseñauser;
    private javax.swing.JTextField digitoverificadorventas;
    private javax.swing.JTextField direccion_destinventa;
    private javax.swing.JLabel direcciondestinario;
    private javax.swing.JLabel emailventassolicitante;
    private javax.swing.JComboBox<String> entregahora_ventas;
    private javax.swing.JLabel estadodespacholetra;
    private com.toedter.calendar.JDateChooser fecha_entrega_venta;
    private javax.swing.JLabel fechaentregadestinarios;
    private javax.swing.JLabel fechapagoletra;
    private javax.swing.JLabel guionmedio;
    private javax.swing.JLabel horaentrega;
    private javax.swing.JLabel horafinentregaletra;
    private javax.swing.JLabel horainicioletra;
    private javax.swing.JComboBox<String> hrsentrega_ventas;
    private javax.swing.JLabel hrsletra;
    private javax.swing.JPanel informes;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel letralogoadministrador;
    private javax.swing.JLabel letraslogocompras;
    private javax.swing.JLabel logoletraconfirmacion;
    private javax.swing.JLabel logosinformes;
    private javax.swing.JLabel nameclienteventa;
    private javax.swing.JTextField namedestinarios_venta;
    private javax.swing.JLabel namedestinarioventa;
    private javax.swing.JLabel nameuser;
    private javax.swing.JLabel nombreclienteletras;
    private javax.swing.JLabel numeropedidoletra;
    private javax.swing.JLabel numeropedidosventa;
    private javax.swing.JLabel numeroventascliente;
    private javax.swing.JPanel pack;
    private javax.swing.JComboBox<String> packdestinario;
    private javax.swing.JLabel packletras;
    private javax.swing.JTabbedPane panelconfirmacion;
    private javax.swing.JScrollPane paneldespacho;
    private javax.swing.JPanel paneldespacholistadestino;
    private javax.swing.JPanel panelestadodespacho;
    private javax.swing.JPanel panellogo;
    private javax.swing.JTable panelpendientpago;
    private javax.swing.JScrollPane paneltablapendientepago;
    private javax.swing.JPanel panelusuarios;
    private javax.swing.JPanel panelventas;
    private javax.swing.JPanel primerpanellistadestino;
    private javax.swing.JPanel proveedores;
    private javax.swing.JLabel repetircontraseña;
    private javax.swing.JPanel rrss;
    private javax.swing.JLabel rutconfirmapagoletra;
    private javax.swing.JLabel rutventassolicitante;
    private javax.swing.JLabel saludosletra;
    private javax.swing.JButton seleccionarconfirmacion;
    private javax.swing.JTable tabla;
    private javax.swing.JTable tabladespacho;
    private javax.swing.JScrollPane tabladespachodia;
    private javax.swing.JTable tabladespachodiadestino;
    private javax.swing.JLabel titulodespachopordia;
    private javax.swing.JPasswordField txt2contraseña;
    private javax.swing.JTextField txtbuscardespacho;
    private javax.swing.JTextField txtbuscardestino;
    private javax.swing.JTextField txtbuscaruserregistrados;
    private javax.swing.JPasswordField txtcontraseña;
    private javax.swing.JTextField txtnamecliente;
    private javax.swing.JTextField txtnumeropedido_confirmacion;
    private javax.swing.JTextField txtrutconfirmacion;
    private javax.swing.JTextField txtsaludos;
    private javax.swing.JTextField txtusuario;
    private javax.swing.JPanel usuario;
    private javax.swing.JTabbedPane usuarios;
    private javax.swing.JPanel usuariosregistrados;
    private javax.swing.JScrollPane usuariosregistradostabla;
    private javax.swing.JPanel ventanaventa_datosdestinarios;
    private javax.swing.JPanel ventanaventa_datossolicitantes;
    private javax.swing.JPanel ventas;
    private javax.swing.JPanel ventaspendientepago;
    private javax.swing.JLabel ventpendientpagoletras;
    // End of variables declaration//GEN-END:variables
}
